using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Frank.SourceGenerators.Localization.Internals;

internal static class TypeDeclarationHelper
{
    public static SourceText PrepareTypeDeclarationSyntax<TSyntax>(TSyntax syntax, string rootNamespace)
        where TSyntax : MemberDeclarationSyntax =>
        SourceText.From(SyntaxFactory
            .CompilationUnit()
            .AddUsings(
                SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System")).WithLeadingTrivia(SyntaxFactory.Comment("// <auto-generated />")),
                SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System.ComponentModel")),
                SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System.Globalization")),
                SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System.Linq")),
                SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System.Collections.Generic")),
                SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System.Collections"))
            )
            .AddMembers(SyntaxFactory.NamespaceDeclaration(SyntaxFactory.ParseName(rootNamespace))
                .AddMembers(syntax))
            .NormalizeWhitespace()
            .ToFullString(), System.Text.Encoding.UTF8);
}