
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RUN_NUMBER: ${{ github.run_number }}
  VERSION: ""
  YEAR: ""
  MONTH: ""
  DAY: ""

jobs:  
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: echo "FOO=bar" >> $GITHUB_ENV

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Use environment variable
        run: echo $FOO
  setup:
    name: Setup
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Current Time
      uses: josStorer/get-current-time@v2.1.1
      id: current-time
      with:
        format: YYYYMMDD
        utcOffset: "00:00"
    - name: Use current time
      env:
        YEAR: "${{ steps.current-time.outputs.year }}"
        MONTH: "${{ steps.current-time.outputs.month }}"
        DAY: "${{ steps.current-time.outputs.day }}"
        VERSION: "${{ env.YEAR }}.${{ env.MONTH }}.${{ env.DAY }}.${{ env.RUN_NUMBER }}"
      run: echo "${{ env.VERSION }}"
  build:
    needs: setup
    name: Build ${{ vars.env.VERSION }} 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      working-directory: ./Frank.SourceGenerator.AdditionalFiles/
      run: dotnet restore

    - name: Build
      working-directory: ./Frank.SourceGenerator.AdditionalFiles/
      run: dotnet build --configuration Release --no-restore /p:Version=${{ env.VERSION }}

    - name: Test
      working-directory: ./Frank.SourceGenerator.AdditionalFiles/
      run: dotnet test --no-build

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Pack
      working-directory: ./Frank.SourceGenerator.AdditionalFiles/
      run: dotnet pack --configuration Release --no-build --output nupkgs /p:PackageVersion=${{ env.VERSION }}

  publish:
    needs: package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push NuGet
      working-directory: ./Frank.SourceGenerator.AdditionalFiles/
      run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json --skip-duplicate
